stages:
  - stage: stage1
    pool: 
      vmImage: 'ubuntu-latest'
    jobs:
    - job: job1
      steps:
        - script: echo 'rodando  job1 a pelo template'
    - job: job2
      steps:
        - script: echo 'rodando job2 a pelo  template'
        